languages: java

jdk:
  - oraclejdk8
sudo: false
script: mvn clean package -DskipTests

cache:
  directories:
    - $HOME/.m2/repository

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/facebook