language: java
#language: minimal

env:
  global:
    - MAVEN_OPTS="-Xmx2g -XX:+ExitOnOutOfMemoryError"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"

sudo: required

dist: trusty


cache:
  directories:
    - $HOME/.m2/repository

install:
  - mvn -v

script:
  df -h && mvn install -DskipTests

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/facebook
